language: d
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev
dist: trusty
d:
  - dmd
  - dmd-beta
  - ldc
  - gdc
matrix:
  allow_failures:
    - d: dmd-beta
    - d: ldc
    - d: gdc
services:
  - mysql
  - postgresql
before_script:
  - psql -c 'create database postgrestest;' -U postgres
  - mysql -e 'CREATE DATABASE mysqltest;'
env:
  - MYHOST=127.0.0.1
script:
  - dub test -b unittest-cov --combined
  - dub fetch doveralls
  - dub run doveralls
