language: d
sudo: false
d:
  - dmd
  - dmd-beta
  - ldc
  - gdc
matrix:
  allow_failures:
    - d: dmd-beta
    - d: ldc
    - d: gdc
services:
  - mysql
  - postgresql
before_script:
  - psql -c 'create database postgrestest;' -U postgres
  - mysql -e 'CREATE DATABASE mysqltest;'
env:
  - MYHOST=127.0.0.1
install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.1/doveralls_linux_travis"
  - chmod +x doveralls
script:
  - dub test -b unittest-cov --combined
  - ./doveralls