language: d
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - unixodbc
dist: trusty
d:
  - dmd
  - dmd-beta
  - ldc
  - gdc
matrix:
  allow_failures:
    - d: dmd-beta
    - d: ldc
    - d: gdc
script:
  - dub test -b unittest-cov --combined
  - dub fetch doveralls
  - dub run doveralls
